/**
 * Icon Constants
 *
 * Curated icon categories for activity tiles and custom components.
 * Uses lucide-react icon names.
 */

// Curated icon categories with ~100 useful icons for activities
export const ICON_CATEGORIES = {
  Activities: [
    'Bike',
    'Dumbbell',
    'Music',
    'Gamepad2',
    'Palette',
    'Camera',
    'Headphones',
    'Guitar',
    'Mic',
    'Footprints',
    'Mountain',
    'Tent',
    'Fish',
    'Bird',
    'Dog',
    'Cat',
  ],
  Work: [
    'Briefcase',
    'Laptop',
    'Code',
    'PenTool',
    'Building',
    'Monitor',
    'Keyboard',
    'FileText',
    'FolderOpen',
    'Mail',
    'Send',
    'Phone',
    'Video',
    'Calendar',
    'Clock',
    'Timer',
    'Target',
    'Flag',
    'Award',
    'Trophy',
  ],
  Lifestyle: [
    'Coffee',
    'Wine',
    'Utensils',
    'ShoppingBag',
    'ShoppingCart',
    'Gift',
    'Shirt',
    'Scissors',
    'Gem',
    'Crown',
    'Star',
    'Heart',
    'Smile',
    'Meh',
    'Frown',
    'ThumbsUp',
    'PartyPopper',
    'Cake',
    'Cookie',
    'Pizza',
    'Apple',
  ],
  Wellness: [
    'Moon',
    'Sun',
    'CloudSun',
    'Sunrise',
    'Brain',
    'Eye',
    'Ear',
    'Activity',
    'Pill',
    'Stethoscope',
    'Thermometer',
    'Droplet',
    'Leaf',
    'Flower',
    'TreePine',
    'Sprout',
    'Wind',
    'Waves',
    'Flame',
    'Snowflake',
    'Zap',
  ],
  Social: [
    'Users',
    'UserPlus',
    'MessageCircle',
    'MessagesSquare',
    'AtSign',
    'Share2',
    'Link',
    'Globe',
    'MapPin',
    'Navigation',
    'Compass',
    'Home',
    'Building2',
    'Church',
    'Landmark',
    'School',
    'GraduationCap',
    'BookOpen',
    'Library',
  ],
  Travel: [
    'Plane',
    'Car',
    'Train',
    'Bus',
    'Ship',
    'Anchor',
    'Map',
    'Luggage',
    'Ticket',
    'Hotel',
    'Bed',
    'Sofa',
    'Armchair',
    'Lamp',
    'Tv',
    'Radio',
    'Wifi',
    'Battery',
    'Plug',
    'Power',
    'Lightbulb',
  ],
} as const;

// Flatten all icons for search
export const ALL_ICONS = Object.values(ICON_CATEGORIES).flat();

// Type for icon category keys
export type IconCategory = keyof typeof ICON_CATEGORIES | 'All';
