// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/aman1117/growth-tracker"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgot-password": {
            "post": {
                "description": "Send password reset email (always returns success for security)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Request password reset",
                "parameters": [
                    {
                        "description": "User email",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reset email sent (if user exists)",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "description": "Reset password using the token from email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Reset password with token",
                "parameters": [
                    {
                        "description": "Reset token and new password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password reset successful",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid token or validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change the authenticated user's password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "description": "Current and new password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password changed successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error or incorrect password",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/create-activity": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Log hours for a specific activity on a date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activities"
                ],
                "summary": "Create or update an activity",
                "parameters": [
                    {
                        "description": "Activity details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.CreateActivityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Activity updated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-activities": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve activities for a user within a date range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activities"
                ],
                "summary": "Get activities for a user",
                "parameters": [
                    {
                        "description": "Date range and username",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.GetActivitiesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of activities",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ActivityDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation error or user not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Private account",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-bio": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get current user's bio",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get bio",
                "responses": {
                    "200": {
                        "description": "Bio content",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.BioResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-privacy": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get current account privacy setting",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get privacy setting",
                "responses": {
                    "200": {
                        "description": "Privacy setting",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.PrivacyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-streak": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve streak information for a user on a specific date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Streaks"
                ],
                "summary": "Get streak data",
                "parameters": [
                    {
                        "description": "Username and date",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.GetStreakRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Streak data",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.StreakResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error or streak not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Private account",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-week-analytics": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve weekly analytics including daily breakdown and activity summary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Get weekly analytics",
                "parameters": [
                    {
                        "description": "Username and week start date",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.GetWeekAnalyticsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Weekly analytics data",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.WeekAnalyticsResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error or user not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Private account",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticate user with email/username and password, returns JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful with JWT token",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get full profile of authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "User profile",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Create a new user account with email, username, and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error or user exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tile-config": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get dashboard tile configuration for authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tile Config"
                ],
                "summary": "Get tile configuration",
                "responses": {
                    "200": {
                        "description": "Tile configuration",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.TileConfigResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save dashboard tile configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tile Config"
                ],
                "summary": "Save tile configuration",
                "parameters": [
                    {
                        "description": "Tile configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.SaveTileConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Config saved",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tile-config/user": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get dashboard tile configuration for another user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tile Config"
                ],
                "summary": "Get tile config by username",
                "parameters": [
                    {
                        "description": "Target username",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.GetTileConfigByUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tile configuration",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.TileConfigResponse"
                        }
                    },
                    "400": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Private account",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/update-bio": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user bio (max 150 characters)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Update bio",
                "parameters": [
                    {
                        "description": "Bio content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.UpdateBioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bio updated",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.BioResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/update-privacy": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Set account privacy (public or private)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Update privacy setting",
                "parameters": [
                    {
                        "description": "Privacy setting",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.UpdatePrivacyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Privacy updated",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.PrivacyResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/update-username": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the authenticated user's username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Update username",
                "parameters": [
                    {
                        "description": "New username",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.UpdateUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Username updated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.UsernameUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error or username taken",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Search for users by username (excludes private accounts)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Search users",
                "parameters": [
                    {
                        "description": "Search query",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.SearchUsersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of users",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.UserDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_aman1117_backend_internal_dto.ActivityDTO": {
            "description": "Activity data",
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2026-01-04"
                },
                "hours": {
                    "type": "number",
                    "example": 2.5
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ActivityName"
                        }
                    ],
                    "example": "study"
                },
                "note": {
                    "type": "string",
                    "example": "Worked on Go project"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.ActivitySummary": {
            "description": "Aggregated activity summary",
            "type": "object",
            "properties": {
                "name": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ActivityName"
                        }
                    ],
                    "example": "study"
                },
                "total_hours": {
                    "type": "number",
                    "example": 15.5
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.BioResponse": {
            "description": "Bio retrieval result",
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string",
                    "example": "Software developer | Coffee enthusiast"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.ChangePasswordRequest": {
            "description": "Change password for authenticated user",
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string",
                    "example": "OldPass123"
                },
                "new_password": {
                    "type": "string",
                    "example": "NewPass123"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.CreateActivityRequest": {
            "description": "Create or update an activity",
            "type": "object",
            "properties": {
                "activity": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ActivityName"
                        }
                    ],
                    "example": "study"
                },
                "date": {
                    "description": "Format: YYYY-MM-DD",
                    "type": "string",
                    "example": "2026-01-04"
                },
                "hours": {
                    "type": "number",
                    "example": 2.5
                },
                "note": {
                    "type": "string",
                    "example": "Worked on Go project"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.DataResponse": {
            "description": "Generic response with data payload",
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.DayActivityBreakdown": {
            "description": "Activity breakdown for a day",
            "type": "object",
            "properties": {
                "hours": {
                    "type": "number",
                    "example": 2.5
                },
                "name": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ActivityName"
                        }
                    ],
                    "example": "study"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.DayAnalytics": {
            "description": "Daily analytics data",
            "type": "object",
            "properties": {
                "activities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.DayActivityBreakdown"
                    }
                },
                "date": {
                    "type": "string",
                    "example": "2026-01-04"
                },
                "day_name": {
                    "type": "string",
                    "example": "Sat"
                },
                "total_hours": {
                    "type": "number",
                    "example": 8.5
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.ErrorResponse": {
            "description": "Generic error response",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                },
                "error_code": {
                    "type": "string",
                    "example": "INVALID_REQUEST"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.ForgotPasswordRequest": {
            "description": "Password reset request initiation",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.GetActivitiesRequest": {
            "description": "Get activities for a date range",
            "type": "object",
            "properties": {
                "end_date": {
                    "description": "Format: YYYY-MM-DD",
                    "type": "string",
                    "example": "2026-01-07"
                },
                "start_date": {
                    "description": "Format: YYYY-MM-DD",
                    "type": "string",
                    "example": "2026-01-01"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.GetStreakRequest": {
            "description": "Get streak data for a specific date",
            "type": "object",
            "properties": {
                "date": {
                    "description": "Format: YYYY-MM-DD",
                    "type": "string",
                    "example": "2026-01-04"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.GetTileConfigByUsernameRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.GetWeekAnalyticsRequest": {
            "description": "Get weekly analytics starting from a specific Monday",
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "example": "john_doe"
                },
                "week_start": {
                    "description": "Format: YYYY-MM-DD (Monday of the week)",
                    "type": "string",
                    "example": "2025-12-30"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.LoginRequest": {
            "description": "User login request",
            "type": "object",
            "properties": {
                "identifier": {
                    "description": "Can be email or username",
                    "type": "string",
                    "example": "john_doe"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePass123"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.LoginResponse": {
            "description": "Successful login response with JWT token",
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "expires_at": {
                    "type": "string",
                    "example": "2026-01-05T12:00:00Z"
                },
                "expires_in": {
                    "description": "seconds",
                    "type": "integer",
                    "example": 86400
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.PrivacyResponse": {
            "description": "Privacy setting result",
            "type": "object",
            "properties": {
                "is_private": {
                    "type": "boolean",
                    "example": false
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.ProfileResponse": {
            "description": "User profile information",
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string",
                    "example": "Software developer"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "profile_pic": {
                    "type": "string",
                    "example": "https://storage.blob.core.windows.net/pics/1/abc.jpg"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.RegisterRequest": {
            "description": "User registration request",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePass123"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.ResetPasswordRequest": {
            "description": "Password reset with token",
            "type": "object",
            "properties": {
                "confirm_password": {
                    "type": "string",
                    "example": "NewSecurePass123"
                },
                "new_password": {
                    "type": "string",
                    "example": "NewSecurePass123"
                },
                "token": {
                    "type": "string",
                    "example": "abc123def456"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.SaveTileConfigRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/models.JSONB"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.SearchUsersRequest": {
            "description": "Search for users by username",
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "example": "john"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.StreakDTO": {
            "description": "Streak information",
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer",
                    "example": 7
                },
                "date": {
                    "type": "string",
                    "example": "2026-01-04"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "longest": {
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.StreakInfo": {
            "description": "Streak information in analytics",
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer",
                    "example": 7
                },
                "longest": {
                    "type": "integer",
                    "example": 30
                },
                "longest_end": {
                    "type": "string",
                    "example": "2025-12-30"
                },
                "longest_start": {
                    "type": "string",
                    "example": "2025-12-01"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.StreakResponse": {
            "description": "Streak data response",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.StreakDTO"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.SuccessResponse": {
            "description": "Generic success response",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.TileConfigResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.JSONB"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.UpdateBioRequest": {
            "description": "Bio update request",
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string",
                    "example": "Software developer | Coffee enthusiast"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.UpdatePrivacyRequest": {
            "description": "Privacy setting update request",
            "type": "object",
            "properties": {
                "is_private": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.UpdateUsernameRequest": {
            "description": "Username update request",
            "type": "object",
            "properties": {
                "new_username": {
                    "type": "string",
                    "example": "new_username"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.UserDTO": {
            "description": "User information for search results",
            "type": "object",
            "properties": {
                "bio": {
                    "description": "Only included for public profiles",
                    "type": "string",
                    "example": "Software developer"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_private": {
                    "type": "boolean",
                    "example": false
                },
                "profile_pic": {
                    "type": "string",
                    "example": "https://storage.blob.core.windows.net/pics/1/abc.jpg"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.UsernameUpdateResponse": {
            "description": "Username update result",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Username updated successfully"
                },
                "new_username": {
                    "type": "string",
                    "example": "new_username"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_aman1117_backend_internal_dto.WeekAnalyticsResponse": {
            "description": "Weekly analytics data",
            "type": "object",
            "properties": {
                "activity_summary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.ActivitySummary"
                    }
                },
                "daily_breakdown": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.DayAnalytics"
                    }
                },
                "is_current_week": {
                    "type": "boolean",
                    "example": true
                },
                "percentage_change": {
                    "type": "number",
                    "example": 11.84
                },
                "percentage_vs_current": {
                    "type": "number",
                    "example": 0
                },
                "streak": {
                    "$ref": "#/definitions/github_com_aman1117_backend_internal_dto.StreakInfo"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "total_hours_current_week": {
                    "type": "number",
                    "example": 42.5
                },
                "total_hours_prev_week": {
                    "type": "number",
                    "example": 38
                },
                "total_hours_this_week": {
                    "type": "number",
                    "example": 42.5
                }
            }
        },
        "models.ActivityName": {
            "type": "string",
            "enum": [
                "sleep",
                "study",
                "book_reading",
                "eating",
                "friends",
                "grooming",
                "workout",
                "reels",
                "family",
                "idle",
                "creative",
                "travelling",
                "errand",
                "rest",
                "entertainment",
                "office"
            ],
            "x-enum-varnames": [
                "ActivitySleep",
                "ActivityStudy",
                "ActivityBookReading",
                "ActivityEating",
                "ActivityFriends",
                "ActivityGrooming",
                "ActivityWorkout",
                "ActivityReels",
                "ActivityFamily",
                "ActivityIdle",
                "ActivityCreative",
                "ActivityTravelling",
                "ActivityErrand",
                "ActivityRest",
                "ActivityEntertainment",
                "ActivityOffice"
            ]
        },
        "models.JSONB": {
            "type": "object",
            "additionalProperties": true
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Growth Tracker API",
	Description:      "API for tracking daily activities, streaks, and analytics.\n\n## Features\n- User authentication with JWT tokens\n- Activity tracking with customizable types\n- Streak tracking to maintain consistency\n- Weekly analytics with daily breakdowns\n- Privacy controls for user profiles\n- Tile configuration for dashboard customization\n\n## Rate Limits\n- Login/Register: 5 requests per minute per IP\n- Password Reset: 3 requests per minute per IP\n- General API: 60 requests per minute per user",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
