/**
 * PushNotificationSettings Styles
 *
 * CSS-in-JS styles for the push notification settings components.
 */

import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  section: {
    background: 'var(--bg-secondary)',
    borderRadius: '10px',
    padding: '0.75rem',
    border: '1px solid var(--border)',
  },
  sectionTitle: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: 'var(--text-tertiary)',
    marginBottom: '0.5rem',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0.5rem 0',
  },
  rowWithBorder: {
    borderBottom: '1px solid var(--border)',
  },
  rowInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.125rem',
    flex: 1,
    minWidth: 0,
  },
  rowLabel: {
    fontSize: '0.875rem',
    fontWeight: 500,
    color: 'var(--text-primary)',
  },
  rowDescription: {
    fontSize: '0.75rem',
    color: 'var(--text-tertiary)',
  },
  toggle: {
    position: 'relative',
    width: '40px',
    height: '22px',
    backgroundColor: 'var(--toggle-off-bg)',
    borderRadius: '11px',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    border: 'none',
    padding: 0,
    flexShrink: 0,
  },
  toggleActive: {
    backgroundColor: 'var(--accent)',
  },
  toggleDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  toggleKnob: {
    position: 'absolute',
    top: '2px',
    left: '2px',
    width: '18px',
    height: '18px',
    backgroundColor: 'white',
    borderRadius: '50%',
    transition: 'transform 0.2s ease',
    boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
  },
  toggleKnobActive: {
    transform: 'translateX(18px)',
  },
  errorBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.625rem 0.75rem',
    background: 'var(--error-bg, rgba(239, 68, 68, 0.1))',
    borderRadius: '8px',
    border: '1px solid var(--error-border, rgba(239, 68, 68, 0.2))',
  },
  errorIcon: {
    color: 'var(--error-color, #ef4444)',
    flexShrink: 0,
  },
  errorText: {
    fontSize: '0.8125rem',
    color: 'var(--error-color, #ef4444)',
    lineHeight: 1.4,
  },
  enableButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    width: '100%',
    padding: '0.75rem 1rem',
    backgroundColor: 'var(--accent)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '0.875rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'opacity 0.2s ease',
  },
  enableButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  quietHoursRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    paddingTop: '0.5rem',
  },
  timeSelect: {
    padding: '0.375rem 0.5rem',
    borderRadius: '6px',
    border: '1px solid var(--border)',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
    fontSize: '0.8125rem',
    cursor: 'pointer',
  },
  timeLabel: {
    fontSize: '0.8125rem',
    color: 'var(--text-tertiary)',
  },
  accordionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '0.625rem 0.75rem',
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
    color: 'var(--text-primary)',
  },
  accordionTitle: {
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: 'inherit',
  },
  accordionChevron: {
    color: 'var(--text-secondary)',
    transition: 'transform 0.2s ease',
  },
  accordionSummary: {
    fontSize: '0.75rem',
    color: 'var(--text-tertiary)',
  },
  inlineAccordion: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
    padding: 0,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: 'var(--text-primary)',
  },
  expandedCard: {
    background: 'var(--bg-tertiary)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  expandedCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '0.625rem 0.75rem',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: 'var(--text-primary)',
  },
  expandedCardContent: {
    padding: '0 0.75rem 0.5rem 0.75rem',
    borderTop: '1px solid var(--border)',
  },
  compactRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0.375rem 0',
  },
  compactLabel: {
    fontSize: '0.8125rem',
    color: 'var(--text-secondary)',
  },
  accordionContent: {
    overflow: 'hidden',
    transition: 'max-height 0.2s ease, opacity 0.2s ease, padding 0.2s ease',
  },
};
